
- name: create config directories
  file:
    dest: /home/vagrant/r_eureka/config/
    mode: 0775
    recurse: yes
    state: directory

- name: create app directories
  file:
    dest: /home/vagrant/r_eureka/app/
    mode: 0775
    recurse: yes
    state: directory

- name: insert config file
  template:
    src: eureka/application.properties.j2
    dest: /home/vagrant/r_eureka/config/application.properties
    mode: 0755
    
- name: install-deploy jar
  maven_artifact:
    group_id: com.company
    artifact_id: eurekaServer
    repository_url: 'http://192.168.5.6:8081/repository/ihd_snapshots/'
    username: admin
    password: admin
    dest: /home/vagrant/r_eureka/app/eurekaServer*.jar
    
- name: run eureka jar
  shell: java -jar /home/vagrant/r_eureka/app/eurekaServer*.jar --spring.config.name=application --spring.config.location=file:////home/vagrant/r_eureka/config


#- name: wait for instance
#  uri:
#    url: "http://127.0.0.1:8080/"
#    status_code: 404
#  register: result
#  until: result.status == 404
#  retries: 120
#  delay: 1

