
- name: create config directories
  file:
    dest: /home/vagrant/r_eureka/config/
    mode: 0775
    recurse: yes
    state: directory

- name: create app directories
  file:
    dest: /home/vagrant/r_eureka/app/
    mode: 0775
    recurse: yes
    state: directory

- name: insert config file
  template:
    src: eureka/application.properties.j2
    dest: /home/vagrant/r_eureka/config/application.properties
    mode: 0755
    
- name: getting runnig version process
  shell: "ps -ef | grep -v grep | grep -w eurekaServer.jar | awk '{print $2}'"
  register: running_processes

- name: kill running version
  shell: kill -9 {{ item }}
  with_items: "{{ running_processes.stdout_lines }}"

- name: remove  existing jar to avoid idempotence
  file:
    state: absent
    path: /home/vagrant/r_eureka/app/*

- name: install-deploy jar
  maven_artifact:
    group_id: com.example.eureka
    artifact_id: eurekaServer
    repository_url: {{ nexus_url }}
    version: {{ version_to_deploy }}
    dest: /home/vagrant/r_eureka/app/eurekaServer.jar
    mode: 0755

- name: run eureka jar
  shell: nohup java -jar /home/vagrant/r_eureka/app/eurekaServer.jar --spring.config.name=application --spring.config.location=file:////home/vagrant/r_eureka/config/ &

- name: wait for instance
  uri:
    url: {{ eureka.host }}
    status_code: 200
  register: result
  until: result.status == 200
  retries: 120
  delay: 1

